create table if not exists public.driver_signins (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  company_carrier text not null,
  driver_name text not null,
  rego text not null,
  movement_type text not null check (movement_type in ('Drop Off','Pick Up')),
  quantity integer not null check (quantity > 0),
  load_type text not null check (load_type in ('Pallets','Cartons','Cages','Bins','Satchels')),
  reference_no text null,
  declaration_accepted boolean not null default false,
  source text not null default 'manual_web'
);

create table if not exists public.coordinator_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.driver_signins enable row level security;
alter table public.coordinator_users enable row level security;

drop policy if exists "Public can submit driver sign-ins" on public.driver_signins;
create policy "Public can submit driver sign-ins"
on public.driver_signins for insert to anon, authenticated
with check (declaration_accepted = true and quantity > 0);

drop policy if exists "Coordinators can view driver sign-ins" on public.driver_signins;
create policy "Coordinators can view driver sign-ins"
on public.driver_signins for select to authenticated
using (
  exists (
    select 1 from public.coordinator_users cu
    where cu.user_id = auth.uid() and cu.active = true
  )
);

drop policy if exists "Coordinator can read own access record" on public.coordinator_users;
create policy "Coordinator can read own access record"
on public.coordinator_users for select to authenticated
using (user_id = auth.uid());

-- No update/delete policies are created.
-- After creating a coordinator in Supabase Authentication, add them like this:
-- insert into public.coordinator_users (user_id, email)
-- values ('AUTH-USER-UUID-HERE', 'coordinator@company.com');
